const incidents = [
  "UNKNOWN",
  "ACCIDENT",
  "FOG",
  "DANGEROUS_CONDITIONS",
  "RAIN",
  "ICE",
  "JAM",
  "LANE_CLOSED",
  "ROAD_CLOSED",
  "ROAD_WORKS",
  "WIND",
  "FLOODING",
  "DETOUR",
  "CLUSTER",
  "HELP"
]

const severities = ["UNKNOWN", "MINOR", "MODERATE", "MAJOR", "UNDEFINED" ];

const randomSeverity = () => Math.floor(Math.random() * 5);

const randomIncident = () => Math.floor(Math.random() * 15);

const randomDate = () => {
  const start = new Date(1561873688925);
  const end = new Date(1561967257075);
  const startHour = 8;
  const endHour = 10;
  let date = new Date(+start + Math.random() * (end - start));
  let hour = startHour + Math.random() * (endHour - startHour) | 0;
  date.setHours(hour);
  return date.getTime();
}

export default [
  {
    "description": null,
    "id": "00001",
    "latitude": "47.150532",
    "longitude": "27.586770",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "00002",
    "latitude": "47.179074",
    "longitude": "27.568590",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "00003",
    "latitude": "47.173670",
    "longitude": "27.573159",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "00004",
    "latitude": "47.166045",
    "longitude": "27.570864",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "00005",
    "latitude": "47.160913",
    "longitude": "27.573153",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "00006",
    "latitude": "47.155762",
    "longitude": "27.577841",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "00007",
    "latitude": "47.154974",
    "longitude": "27.573539",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "00008",
    "latitude": "47.151662",
    "longitude": "27.572724",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "00009",
    "latitude": "47.148276",
    "longitude": "27.576715",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000010",
    "latitude": "47.148276",
    "longitude": "27.576715",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000011",
    "latitude": "47.145069",
    "longitude": "27.582205",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000012",
    "latitude": "47.136246",
    "longitude": "27.582441",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000013",
    "latitude": "47.147321",
    "longitude": "27.584223",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000014",
    "latitude": "47.151232",
    "longitude": "27.589169",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000015",
    "latitude": "47.155026",
    "longitude": "27.586519",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000016",
    "latitude": "47.158404",
    "longitude": "27.585918",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000017",
    "latitude": "47.159749",
    "longitude": "27.588230",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000018",
    "latitude": "47.151232",
    "longitude": "27.589169",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000019",
    "latitude": "47.164213",
    "longitude": "27.581310",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000020",
    "latitude": "47.167014",
    "longitude": "27.584400",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000021",
    "latitude": "47.165803",
    "longitude": "27.579808",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000022",
    "latitude": "47.175174",
    "longitude": "27.578433",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000023",
    "latitude": "47.190867",
    "longitude": "27.558889",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000024",
    "latitude": "47.176808",
    "longitude": "27.576008",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000025",
    "latitude": "47.176137",
    "longitude": "27.572918",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000026",
    "latitude": "47.180640",
    "longitude": "27.573683",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000027",
    "latitude": "47.179243",
    "longitude": "27.577993",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000028",
    "latitude": "47.174914",
    "longitude": "27.582627",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000029",
    "latitude": "47.180468",
    "longitude": "27.573337",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000030",
    "latitude": "47.181139",
    "longitude": "27.562544",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  },
  {
    "description": null,
    "id": "000031",
    "latitude": "47.186026",
    "longitude": "27.562451",
    "phoneNumber": null,
    "registered": randomDate(),
    "severity": severities[randomSeverity()],
    "title": null,
    "type": incidents[randomIncident()],
  }
]